Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-04, with the labels that each got.

#419 RSE-1053: Fix create activity
  ang/civicase-base/providers/case-type.provider.js
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/test/civicase-base/services/case-type.service.spec.js
Labels: bug

#420 CPS-155: Fix draft email assignee
  CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
  CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
  CRM/Civicase/Hook/alterAPIPermissions/Case.php
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
  css/civicase.min.css
  scss/components/_draft-activity-panel.scss
Labels: bug

#417 RSE-1051: Release v1.0.0-beta.5
  CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
  CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
  CRM/Civicase/Hook/alterAPIPermissions/Case.php
  ang/civicase-base/providers/case-type.provider.js
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/test/civicase-base/services/case-type.service.spec.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
  css/civicase.min.css
  info.xml
  scss/components/_draft-activity-panel.scss
Labels: release

#426 CPS-77: Fix for Add Case button in Contact Tab not redirecting to Webforms
  ang/civicase/case/services/add-case.service.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
  ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
  ang/test/civicase/case/services/add-case.service.spec.js
  ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
  ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
Labels: bug

#439 CATL-1321: Fix dashboard tab affix when Admin Menu is visible
  ang/civicase/crm-dashboard/directives/crm-dashboard-tabset-affix.directive.js
Labels: bug

#425 RSE-896: Fix Case tags
  ang/civicase/shared/directives/tags-container.directive.js
  ang/test/civicase/shared/directives/tags-container.directive.spec.js
Labels: bug

#440 CATL-1314: Update Move/Copy activity endpoints
  ang/civicase/activity/actions/services/move-copy-activity-action.service.js
  ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
Labels: enhancement

#433 RSE-1035: Filter Webforms by Case Type
  ang/civicase.ang.php
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/civicase/case/actions/services/webforms-case-action.service.js
  ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js
  ang/test/mocks/data/case-actions.data.js
  ang/test/mocks/data/cases.data.js
  api/v3/Case/Getwebforms.php
Labels: enhancement, improvements

#436 CATL-1178: Fix Contacts Popup not appearing in Activity blocks
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/case/services/cases-utils.service.js
  ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js
  ang/test/civicase/case/card/directives/case-card.directive.spec.js
  ang/test/civicase/case/services/cases-utils.service.spec.js
  ang/test/mocks/data/cases.data.js
Labels: bug, regression

#431 CPS-72: Fix Activity Feed link
  ang/civicase/activity/factories/get-activity-feed-url.factory.js
  ang/test/civicase/activity/factories/get-activity-feed-url.factory.spec.js
Labels: bug, regression

#438 RSE-1027: Show Error Notification when Client cannot be deleted
  ang/civicase-base.ang.php
  ang/civicase-base/services/crm-api.service.js
  ang/civicase.ang.php
  ang/civicase/case/details/directives/case-details.directive.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/global.js
Labels: bug, enhancement

#435 CPS-129: Add Relationship Description to Other Relationships tab
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  api/v3/Case/Getrelations.php
Labels: enhancement

#421 CATL-1171: Exclude deleted cases from search
  ang/civicase/case/search/directives/search.directive.js
Labels: improvements

#434 RSE-1013: Fix 'Disable' link of case type category
  CRM/Civicase/Event/Listener/ActivityFilter.php
  CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php
  CRM/Civicase/Factory/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
  CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
  api/v3/Activity/Getmonthswithactivities.php
  civicase.php
Labels: bug

#446 CPS-33: Set Activity Contact With For Print/Merge Document On Contact actions
  CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
Labels: bug

#424 CPS-146: Remove "To:" field from PDF activity
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
Labels: enhancement

#429 RSE-1002: Add Case Type Category filter to Activity Contact Tab
  CRM/Civicase/Helper/CaseCategory.php
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/activity/filters/directives/activity-filters.directive.html
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/civicase/contact-activity-tab/directives/contact-activity-tab.directive.html
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/civicase/activity/filters/directives/activity-filters.directive.spec.js
  css/civicase.min.css
  package-lock.json
  scss/base/_variables.scss
  scss/components/_activity-filter.scss
Labels: enhancement, improvements

#447 CPS-134: Fix caseid parameter for saving draft and sending emails
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
Labels: bug

#445 CPS-51: Add civicase tabs panel component to dashboard tabs
  css/civicase.min.css
  scss/components/_tabs.scss
  templates/CRM/Civicase/Page/DashboardTabs.tpl
Labels: bug, regression

#450 CPS-180: Fix broken People Tab when certain relationships are present
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase-base/services/case-actions.service.spec.js
  ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
  ang/test/mocks/data/case-actions.data.js
Labels: bug

#443 RSE-1066: Client and activity types word replacement
  CRM/Civicase/Hook/PostProcess/ActivityFormStatusWordReplacement.php
  CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForChangeCase.php
  ang/civicase-base/decorators/root-scope.decorator.js
  ang/civicase-base/replaceable-db-strings/README.md
  ang/civicase-base/replaceable-db-strings/activity-types.js
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/panel/directives/activity-panel.directive.html
  ang/civicase/activity/panel/directives/activity-panel.directive.js
  ang/civicase/case/actions/services/merge-cases-case-action.service.js
  ang/civicase/case/card/directives/case-card-contact-record.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase-base/decorators/root-scope.decorator.spec.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  civicase.php
Labels: enhancement

#451 CPS-196: Fix People tab Bulk Actions
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  css/civicase.min.css
  scss/components/_case-peoples.scss
Labels: bug, regression

#452 CPS-192: Release v1.0.0
  README.md
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  css/civicase.min.css
  info.xml
  scss/components/_case-peoples.scss
Labels: release
