Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-10, with the labels that each got.

#591 RSE-1393: Add unit tests badge
  .github/workflows/unit-test.yml
  README.md
Labels: new feature

#590 CATL-1785: Add Current User Contact Entity And Contact Custom Fields To Tokens
  CRM/Civicase/Hook/Tokens/AddContactTokens.php
  CRM/Civicase/Hook/Tokens/AddContactTokensValues.php
  CRM/Civicase/Service/ContactCustomFieldsProvider.php
  CRM/Civicase/Service/ContactFieldsProvider.php
  civicase.php
  tests/phpunit/CRM/Civicase/Hook/Tokens/AddContactTokenValuesTest.php
  tests/phpunit/CRM/Civicase/Service/ContactCustomFieldsProviderTest.php
Labels: enhancement

#594 RSE-1400: Workflows List page + Misc Improvements
  CRM/Civicase/Page/WorkflowAngular.php
  ang/civicase-base/providers/url-parameters.provider.js
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/shared/directives/on-contact-tab-change.directive.js
  ang/test/civicase-base/providers/url-parameters.provider.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/global.js
  ang/test/karma.conf.js
  ang/test/mocks/data/case-actions.data.js
  ang/test/mocks/data/cases-types.data.js
  ang/test/mocks/services/crm-api.factory.mock.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow.ang.php
  ang/workflow.js
  ang/workflow/action-links/directives/workflow-list-duplicate-action.html
  ang/workflow/action-links/directives/workflow-list-edit-action.html
  ang/workflow/app.routes.js
  ang/workflow/configs/workflow-list-action-items.config.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
  ang/workflow/providers/workflow-list-action-items.provider.js
  css/civicase.min.css
  scss/components/_workflow-list.scss
  templates/CRM/civicase/EditCtrl.hlp
  tests/backstop_data/scenarios/workflow.json
  xml/Menu/civicase.xml
Labels: new feature, run backstop

#588 CATL-1807: Fix Add Case Role button
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
Labels: bug

#598 RSE-1411: Implement Edit Link redirect
  ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
  ang/workflow/action-links/controllers/workflow-edit.controller.js
  ang/workflow/action-links/directives/workflow-list-edit-action.html
Labels: new feature

#601 CATL-1852: Fix limit for adding roles
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
Labels: bug

#600 CATL-1803: Use provided start date when reassigning roles
  CRM/Civicase/Service/CaseRoleCreationPreProcess.php
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
  tests/phpunit/api/v3/CaseRoleCreationTest.php
Labels: bug

#574 CATL-1593: Show inactive roles
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/relationships-tab.directive.html
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/messages.constants.js
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  ang/test/mocks/data/cases.data.js
  ang/test/mocks/data/relationship-type.data.js
  css/civicase.min.css
  scss/components/_case-peoples.scss
Labels: enhancement, run backstop

#575 CATL-1591: Show case role end dates
  CRM/Civicase/Service/CaseRoleCreationPreProcess.php
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
  tests/phpunit/api/v3/CaseRoleCreationTest.php
Labels: enhancement

#585 CATL-1592: Update Case role dates
  CRM/Civicase/Setup/AddChangeCaseRoleDateActivityTypes.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0012.php
  CRM/Civicase/Upgrader/Steps/Step0013.php
  ang/civicase-base/constants.js
  ang/civicase-base/directives/inline-datepicker.directive.js
  ang/civicase-base/directives/send-to-api-on-change.directive.js
  ang/civicase-base/services/remove-date-picker-hrefs.service.js
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/civicase/case/details/people-tab/services/role-dates-updater.service.js
  ang/civicase/letterhead/directives/letterheads-list.directive.html
  ang/civicase/letterhead/directives/letterheads-list.directive.js
  ang/test/civicase-base/directives/inline-datepicker.directive.spec.js
  ang/test/civicase-base/directives/send-to-api-on-change.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  ang/test/civicase/case/details/people-tab/services/role-dates-updater.service.spec.js
  ang/test/global.js
  ang/test/mocks/data/constants.data.js
  ang/test/mocks/data/crm.data.js
  css/civicase.min.css
  package-lock.json
  scss/components/_inline-datepicker.scss
Labels: enhancement

#604 CATL-1579: single case role
  CRM/Civicase/Service/CaseRoleCreationPreProcess.php
  CRM/Civicase/Setup/AddChangeCaseRoleDateActivityTypes.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0012.php
  CRM/Civicase/Upgrader/Steps/Step0013.php
  ang/civicase-base/constants.js
  ang/civicase-base/directives/inline-datepicker.directive.js
  ang/civicase-base/directives/send-to-api-on-change.directive.js
  ang/civicase-base/services/remove-date-picker-hrefs.service.js
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/relationships-tab.directive.html
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/messages.constants.js
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/civicase/case/details/people-tab/services/role-dates-updater.service.js
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/civicase/letterhead/directives/letterheads-list.directive.html
  ang/civicase/letterhead/directives/letterheads-list.directive.js
  ang/test/civicase-base/directives/inline-datepicker.directive.spec.js
  ang/test/civicase-base/directives/send-to-api-on-change.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  ang/test/civicase/case/details/people-tab/services/role-dates-updater.service.spec.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  ang/test/global.js
  ang/test/mocks/data/cases.data.js
  ang/test/mocks/data/constants.data.js
  ang/test/mocks/data/crm.data.js
  ang/test/mocks/data/relationship-type.data.js
  css/civicase.min.css
  package-lock.json
  scss/components/_case-peoples.scss
  scss/components/_inline-datepicker.scss
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
  tests/phpunit/api/v3/CaseRoleCreationTest.php
Labels: enhancement, new feature, run backstop

#599 RSE-1412: Duplicate link functionality
  ang/civicase-base/services/crm-api.service.js
  ang/test/civicase-base/services/crm-api.service.spec.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-month-nav.directive.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  ang/test/civicase/contact/services/contacts-cache.service.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/civicase/shared/directives/panel-query.directive.spec.js
  ang/test/mocks/services/crm-api.factory.mock.js
  ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
  ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow/action-links/controllers/workflow-duplicate.controller.js
  ang/workflow/action-links/directives/workflow-list-duplicate-action.html
  ang/workflow/action-links/directives/workflow-list-duplicate-popup.html
  ang/workflow/action-links/directives/workflow-list-edit-action.html
  ang/workflow/directives/workflow-list.directive.js
  css/civicase.min.css
  scss/components/_workflow-list.scss
  tests/backstop_data/scenarios/workflow.json
Labels: new feature, run backstop

#592 RSE-1296: Add a flag to notify when custom fields are not present
  CRM/Civicase/Form/CaseCategoryTypeCustomField.php
Labels: new feature

#603 RSE-1375: Create New Permissions to access Workflows List page
  CRM/Civicase/Service/CaseCategoryPermission.php
  ang/civicase-base/services/crm-load-form.service.js
  ang/civicase-base/services/crm-url.service.js
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/test/civicase-base/services/crm-load-form.service.spec.js
  ang/test/civicase-base/services/crm-url.service.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
  ang/workflow/action-links/controllers/workflow-duplicate.controller.js
  config/urls/case_category_url.php
  xml/Menu/civicase.xml
Labels: new feature

#605 CPS-347: Release v1.9.2
  info.xml
Labels: release

#615 RSE-1423: Show empty message when no case types are present
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
Labels: bug

#610 CPS-359: Fix case client issues
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
Labels: bug, regression

#611 RSE-1186: Changes to Email Bulk Action
  ang/civicase-base/providers/case-type.provider.js
  ang/civicase-base/services/relationship-type.service.js
  ang/civicase.ang.php
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/case/actions/directives/email-role-selector.html
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/civicase/case/actions/services/email-managers-case-action.service.js
  ang/civicase/case/actions/services/export-cases-case-action.service.js
  ang/civicase/case/actions/services/link-cases-case-action.service.js
  ang/civicase/case/actions/services/lock-cases-case-action.service.js
  ang/civicase/case/actions/services/print-merge-case-action.service.js
  ang/civicase/case/details/directives/case-details.directive.js
  ang/test/civicase-base/providers/case-type.provider.spec.js
  ang/test/civicase-base/services/relationship-type.service.spec.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
  ang/test/civicase/case/actions/services/email-managers-case-action.service.spec.js
  ang/test/civicase/case/actions/services/print-merge-case-action.service.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/mocks/data/cases-types.data.js
  ang/test/mocks/data/relationship-type.data.js
  ang/test/mocks/data/relationship.data.js
  civicase.php
  css/civicase.min.css
  scss/components/_email-role-selector.scss
Labels: new feature

#617 RSE-1380: Add "Manage Workflows" Menu
  CRM/Civicase/Service/CaseCategoryInstance.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Setup/AddManageWorkflowMenu.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0014.php
  package-lock.json
Labels: new feature

#618 CATL-1863: Add case email contacts to front-end settings
  CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
  civicase.php
  js/civicase-settings-form.js
  settings/CiviCase.setting.php
Labels: enhancement

#619 CPS-375: Release v1.9.3
  info.xml
Labels: release, run backstop

#624 CATL-1876: Optimize query for for handling contact involved filter.
  CRM/Civicase/APIHelpers/CaseDetails.php
Labels: enhancement

#626 CATL-1917: Limit relationship remove/reassign end date to today
  CRM/Civicase/Service/CaseRoleCreationPostProcess.php
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
Labels: enhancement
