Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-09, with the labels that each got.

#537 CPS-245: Backstop JS GitHub Action
  .github/workflows/backstop.yml
  .gitignore
  tests/backstop_data/Readme.md
  tests/backstop_data/backstop.tpl.json
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-add-tag.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-remove-tag.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-dropdown.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-client.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-non-client.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-other-relationships-loading.js
  tests/backstop_data/gulp-tasks/backstopjs.js
  tests/backstop_data/package-lock.json
  tests/backstop_data/scenarios/activity-feed-panel.json
  tests/backstop_data/scenarios/contact-case-tab.json
  tests/backstop_data/scenarios/dashboard.json
  tests/backstop_data/scenarios/manage-cases.json
  tests/backstop_data/site-config.json.sample
Labels: new feature, run backstop

#548 FEMS-45: Fix resuming standalone draft email activities
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
Labels: bug

#572 CPS-302: Release v1.8.0
  info.xml
Labels: release

#569 CATL-1674: Allow Single Case Role Setting Only When Multiclient Case Setting Is Single
  CRM/Civicase/Helper/CaseSetting.php
  CRM/Civicase/Hook/PreProcess/AddCaseAdminSettings.php
  js/civicase-settings-form.js
  settings/CiviCase.setting.php
Labels: bug

#571 RSE-1096: Awards Instance support - Frontend solution
  .github/workflows/linters.yml
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/mocks/data/case-category-instance-mapping.data.js
  ang/test/mocks/data/case-category-instance-type.data.js
  phpcs-ruleset.xml
Labels: new feature

#568 CATL-1579: Single Case Role
  CRM/Civicase/Service/CaseRoleCreationPostProcess.php
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
  ang/civicase/case/details/people-tab/services/remove-date-picker-hrefs.service.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  css/civicase.min.css
  package-lock.json
  scss/base/_variables.scss
  scss/components/_contact-prompt-dialog.scss
  scss/components/_date-inputs.scss
  scss/overrides/_clear-link.scss
Labels: new feature, run backstop

#576 CPS-326: Fix self closing html custom tags
  ang/civicase/activity/filters/directives/activity-filters.directive.html
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html
Labels: bug, improvements

#577 CPS-245: Fix source_contact_id error
  tests/backstop_data/gulp-tasks/backstopjs.js
Labels: bug, run backstop

#578 CPS-320: Release v1.9.0
  info.xml
Labels: release

#583 CPS-338: Remove space from npmrc filename
  .npmrc
Labels: bug

#573 CPS-294: Resolve Email Sending Issue In Advance Search
  CRM/Civicase/BAO/Query/CaseCategory.php
Labels: bug

#587 RSE-1309: Fix Issue With Case Category Webform Setting Displaying Category Value Instead Of Name
  CRM/Civicase/BAO/CaseCategoryInstance.php
  CRM/Civicase/Factory/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Hook/BuildForm/AddCaseCategoryInstanceField.php
  CRM/Civicase/Hook/CaseCategoryInstanceBase.php
  CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
  CRM/Civicase/Hook/PostProcess/SaveCaseCategoryInstance.php
  CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryCustomDataType.php
  CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryInstanceUtils.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Service/CaseCategorySetting.php
  CRM/Civicase/Service/CaseManagementUtils.php
  CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Setup/CaseCategoryInstanceSupport.php
  CRM/Civicase/Test/Fabricator/CaseCategory.php
  CRM/Civicase/Upgrader/Steps/Step0012.php
  tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php
Labels: regression

#539 RSE-1118: Award Instance Build
  CRM/Civicase/BAO/CaseCategoryInstance.php
  CRM/Civicase/DAO/CaseCategoryInstance.php
  CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php
  CRM/Civicase/Factory/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Form/CaseCategoryTypeCustomField.php
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Hook/BuildForm/AddCaseCategoryInstanceField.php
  CRM/Civicase/Hook/CaseCategoryInstanceBase.php
  CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
  CRM/Civicase/Hook/PostProcess/SaveCaseCategoryInstance.php
  CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryCustomDataType.php
  CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryInstanceUtils.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Service/CaseCategorySetting.php
  CRM/Civicase/Service/CaseManagementUtils.php
  CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Setup/CaseCategoryInstanceSupport.php
  CRM/Civicase/Test/Fabricator/CaseCategory.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0012.php
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/mocks/data/case-category-instance-mapping.data.js
  ang/test/mocks/data/case-category-instance-type.data.js
  api/v3/CaseCategoryInstance.php
  civicase.php
  phpcs-ruleset.xml
  sql/auto_install.sql
  sql/auto_uninstall.sql
  templates/CRM/Civicase/Form/CaseCategoryInstance.tpl
  tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php
  tests/phpunit/bootstrap.php
  xml/schema/CRM/Civicase/CaseCategoryInstance.entityType.php
  xml/schema/CRM/Civicase/CaseCategoryInstance.xml
Labels: new feature

#589 CPS-335: Release v1.9.1
  info.xml
Labels: release

#586 CATL-1675: Fix Clear Filters Button
  .gitignore
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/case/details/directives/case-details-clear-filters.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/list/directives/case-list-table.directive.html
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
  ang/test/karma.conf.js
  tests/backstop_data/package-lock.json
Labels: bug, regression
