Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-05, with the labels that each got.

#456 RSE-1090: Fix Move/Copy Activity
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Hook/PermissionCheck/ActivityPageView.php
  CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/civicase/activity/actions/services/move-copy-activity-action.html
  ang/civicase/activity/actions/services/move-copy-activity-action.service.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
  civicase.php
  gulpfile.js
  package-lock.json
  package.json
  tests/backstop_data/gulp-tasks/backstopjs.js
  tests/backstop_data/gulpfile.js
  tests/backstop_data/package-lock.json
  tests/backstop_data/package.json
Labels: bug, enhancement

#453 RSE-1081: Fix translations on Contact Page
  CRM/Civicase/Page/ContactCaseTab.php
Labels: bug

#454 RSE-1082: Fix case details placeholder translation
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/summary-tab/case-details-summary-tab.html
Labels: bug

#460 RSE-647: Case Category Type Custom Fields
  CRM/Civicase/Form/CaseCategoryTypeCustomField.php
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
Labels: new feature

#455 RSE-1056: Redirect to case details after creating a case
  CRM/Civicase/Helper/CaseUrl.php
  CRM/Civicase/Hook/PageRun/ViewCasePageRedirect.php
  CRM/Civicase/Hook/PostProcess/RedirectToCaseDetails.php
  ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
  ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
  ang/test/mocks/data/activities.data.js
  ang/test/mocks/data/case-actions.data.js
  civicase.php
Labels: bug, enhancement

#457 CPS-168: Display case list when searching
  ang/civicase/case/search/directives/search.directive.html
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: bug

#464 CPS-166: Fix case settings
  CRM/Civicase/Hook/PreProcess/AddCaseAdminSettings.php
  CRM/Civicase/Service/CaseCategorySetting.php
  civicase.php
  js/civicase-settings-form.js
Labels: enhancement, regression

#463 CATL-1358: Make "Coming Soon" block configurable
  ang/civicase-base.ang.php
  ang/civicase-base/directives/include-replace.directive.js
  ang/civicase-base/providers/case-details-summary-blocks.provider.js
  ang/civicase/case/details/configs/add-case-summary-blocks.config.js
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/case/details/directives/case-details-header.directive.js
  ang/civicase/case/details/directives/case-details-header.html
  ang/civicase/case/details/directives/case-details-placeholder.html
  ang/civicase/case/details/directives/case-details-tabs.directive.html
  ang/civicase/case/details/directives/case-details-tabs.directive.js
  ang/civicase/case/details/directives/case-details-tabs.html
  ang/civicase/case/details/directives/case-details.directive.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/directives/placeholder/activity.html
  ang/civicase/case/details/directives/placeholder/files.html
  ang/civicase/case/details/directives/placeholder/people.html
  ang/civicase/case/details/directives/placeholder/summary.html
  ang/civicase/case/details/directives/tab-content/activity.html
  ang/civicase/case/details/directives/tab-content/files.html
  ang/civicase/case/details/directives/tab-content/people.html
  ang/civicase/case/details/service/case-details-activity-tab.service.js
  ang/civicase/case/details/service/case-details-files-tab.service.js
  ang/civicase/case/details/service/case-details-people-tab.service.js
  ang/civicase/case/details/service/case-details-summary-tab.service.js
  ang/civicase/case/details/summary-tab/case-details-summary-calendar.html
  ang/civicase/case/details/summary-tab/case-details-summary-next-milestone.html
  ang/civicase/case/details/summary-tab/case-details-summary-next-non-milestone-activity.html
  ang/civicase/case/details/summary-tab/case-details-summary-tab.html
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.js
  ang/civicase/case/details/summary-tab/directives/case-summary-other-cases.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-other-cases.directive.js
  ang/civicase/case/details/summary-tab/directives/case-summary-recent-communications.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-recent-communications.directive.js
  ang/civicase/case/details/summary-tab/directives/case-summary-tasks.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-tasks.directive.js
  ang/civicase/case/details/summary-tab/directives/case-summary.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary.directive.js
  ang/test/civicase-base/providers/case-details-summary-blocks.provider.spec.js
  ang/test/civicase-base/providers/case-details-tabs.provider.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  css/civicase.min.css
  package-lock.json
  scss/components/_loading-placeholder.scss
  settings/CiviCase.setting.php
Labels: enhancement, new feature

#458 IN-336: Add linters and unit tests workflows
  .github/workflows/linters.yml
  .github/workflows/unit-test.yml
Labels: new feature

#465 CATL-1348: related case tab setting
  ang/civicase-base.ang.php
  settings/CiviCase.setting.php
Labels: enhancement

#466 CPS-156: People Tab Bugs
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
  api/v3/Case/Getdetails.php
Labels: bug, regression

#468 BASW-634: Civicase Release v1.1.0
  info.xml
Labels: release

#471 BASW-621: Fix for Cases with disabled Case Status
  ang/civicase/case/factories/format-case.factory.js
Labels: bug

#472 CPS-226: Add Karma Unit test github action
  .github/workflows/unit-test.yml
  ang/test/karma.conf.js
Labels: new feature

#469 CATL-1356: Backstop tests for Other Cases block and Tab
  tests/backstop_data/engine_scripts/puppet/on-before.js
  tests/backstop_data/gulp-tasks/backstopjs.js
  tests/backstop_data/scenarios/manage-cases.json
Labels: Backstop, improvements
