Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-07, with the labels that each got.

#480 CATL-1393: Files Tab Download All Bulk Action
  CRM/Civicase/Page/ActivityFiles.php
  ang/civicase/activity/actions/services/download-all-action.service.js
  ang/civicase/activity/actions/services/move-copy-activity-action.service.js
  ang/civicase/activity/actions/services/resume-draft-activity-action.service.js
  ang/civicase/activity/card/directives/activity-card-menu-feed.html
  ang/civicase/case/details/directives/tab-content/files.html
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.js
  ang/civicase/case/details/file-tab/directives/file-filter.directive.html
  ang/civicase/case/details/file-tab/directives/file-filter.directive.js
  ang/civicase/case/details/file-tab/directives/file-list.directive.html
  ang/civicase/case/details/file-tab/directives/file-list.directive.js
  ang/test/civicase/activity/actions/services/download-all-action.service.spec.js
  ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
  ang/test/civicase/activity/actions/services/resume-draft-activity-action.service.spec.js
  ang/test/civicase/case/details/file-tab/directives/case-details-file-tab.directive.spec.js
  ang/test/civicase/case/details/file-tab/directives/file-filter.directive.spec.js
  ang/test/karma.conf.js
  css/civicase.min.css
  package-lock.json
  package.json
  scss/components/_case-files.scss
  scss/components/_checkbox.scss
Labels: enhancement, improvements, new feature

#514 CPS-270: Show webforms without any Case Types
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/civicase/case/actions/services/webforms-case-action.service.js
  ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
  ang/test/mocks/data/case-actions.data.js
  api/v3/Case/Getwebforms.php
Labels: improvements

#512 CPS-252: Make changes to Contact Case Tab
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  css/civicase.min.css
  scss/components/_contact-cases-tab.scss
Labels: new feature

#522 CATL-1494: Fix active tab issue
  ang/civicase/case/details/directives/case-details.directive.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
Labels: bug

#487 CATL-1284: Case Details Tab
  CRM/Civicase/APIHelpers/CustomGroups.php
  CRM/Civicase/APIHelpers/CustomValues.php
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Hook/BuildForm/AddStyleFieldToCaseCustomGroups.php
  CRM/Civicase/Hook/BuildForm/CaseCategoryCustomGroupDisplay.php
  CRM/Civicase/Hook/BuildForm/DisplayAllCustomGroupsInCaseForm.php
  CRM/Civicase/Hook/PageRun/CaseCategoryCustomGroupListing.php
  CRM/Civicase/Hook/alterAPIPermissions/CaseCategory.php
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/directives/tab-content/details.html
  ang/civicase/case/details/service/case-details-details-tab.service.js
  ang/civicase/case/details/summary-tab/case-details-summary-tab.html
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.js
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/civicase/shared/directives/edit-custom-data.directive.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  ang/test/mocks/data/cases.data.js
  api/v3/CustomValue/Getalltreevalues.php
  api/v3/CustomValue/Gettreevalues.php
  civicase.php
  js/custom-group-form.js
  tests/backstop_data/gulp-tasks/backstopjs.js
  tests/backstop_data/scenarios/manage-cases.json
Labels: Backstop, enhancement

#516 CATL-1487: Fix send mail to case client
  ang/civicase/case/services/cases-utils.service.js
  ang/test/civicase/case/services/cases-utils.service.spec.js
Labels: bug

#517 FEMS-37: Fix change case status
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
Labels: bug

#520 CATL-1304: Show popup when clicking on Webform link
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
Labels: improvements

#510 CATL-1466: Add links to email addresses on peoples tab
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
Labels: enhancement

#521 CATL-1293: Activity Feed Contact's Full Name
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
  ang/test/mocks/data/constants.data.js
  css/civicase.min.css
  scss/components/_activity-feed.scss
  scss/components/_contact-card.scss
  settings/CiviCase.setting.php
Labels: enhancement

#524 CATL-1506: Changes to Case Summary Page
  ang/civicase/shared/directives/crm-editable.directive.js
  css/civicase.min.css
  scss/components/_show-more-button.scss
  scss/components/_summary-tab.scss
Labels: improvements, new feature

#528 CPS-1304: Increase popup display time to 30 minutes
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
Labels: improvements

#525 CPS-271: Release v1.3.0
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/civicase/shared/directives/crm-editable.directive.js
  ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
  css/civicase.min.css
  info.xml
  scss/components/_show-more-button.scss
  scss/components/_summary-tab.scss
Labels: release

#530 RSE-1200: Case Category Custom Field Support Cleanup
  CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
  CRM/Civicase/Upgrader.php
Labels: improvements

#531 RSE-647: Case Category Instance Custom Fields
  CRM/Civicase/Form/CaseCategoryTypeCustomField.php
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
  CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
  CRM/Civicase/Upgrader.php
Labels: enhancement

#526 CATL-1504: Change Case Card Activities order
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
Labels: enhancement

#529 CATL-1524: Update tags when model is changed
  ang/civicase-base/directives/tags-selector.directive.js
  ang/test/civicase-base/directives/tags-selector.directive.spec.js
Labels: bug

#527 CATL-1514: Make File Upload Subject Required
  ang/civicase/shared/directives/file-uploader.directive.html
  ang/civicase/shared/directives/file-uploader.directive.js
  ang/test/civicase/shared/directives/file-uploader.directive.spec.js
Labels: enhancement

#538 CPS-283: Release v1.4.0
  info.xml
Labels: release

#541 CATL-1577: Fix Overview Count when filtering by Cases I am Involved In
  CRM/Civicase/APIHelpers/CaseDetails.php
  CRM/Civicase/APIHelpers/CasesByContactInvolved.php
  CRM/Civicase/APIHelpers/ExtendedApi3SelectQuery.php
  api/v3/Case/Getdetailscount.php
  api/v3/Case/Getstats.php
Labels: bug

#534 CATL-1303: Cases I Am Involved to also include activities
  CRM/Civicase/APIHelpers/CaseDetails.php
  CRM/Civicase/APIHelpers/CasesByContactInvolved.php
  CRM/Civicase/APIHelpers/Filters.php
  Civi/CCase/Utils.php
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase/case/search/directives/search.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
  ang/test/mocks/data/constants.data.js
  api/v3/Case/Getdetails.php
  api/v3/Case/Getdetailscount.php
  api/v3/Case/Getstats.php
  settings/CiviCase.setting.php
Labels: bug, enhancement

#540 CATL-1532: Webforms Dropdown Functionality Changes
  ang/civicase/case/actions/services/webforms-case-action.service.js
  ang/civicase/case/details/directives/case-details-header.directive.js
  ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js
  ang/test/civicase/case/details/directives/case-details-header.directive.spec.js
  css/civicase.min.css
  scss/components/_case-header.scss
Labels: enhancement

#543 CATL-1360: Changes to Contacts Card and Case Summary Fields
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/test/civicase/case/card/directives/case-card.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  css/civicase.min.css
  scss/components/_case-custom-fields.scss
  scss/components/_case-summary-fields.scss
  scss/components/_contact-card.scss
Labels: new feature

#544 CPS-295: Release v1.5.0
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/test/civicase/case/card/directives/case-card.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  css/civicase.min.css
  info.xml
  scss/components/_case-custom-fields.scss
  scss/components/_case-summary-fields.scss
  scss/components/_contact-card.scss
Labels: release
