Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-08, with the labels that each got.

#545 CATL-1523: Fix permission error in Files Tab while adding tags
  ang/civicase/shared/directives/file-uploader.directive.js
  ang/test/civicase/shared/directives/file-uploader.directive.spec.js
Labels: bug

#549 CATL-1605: Edit Cases Tags refactoring
  ang/civicase/case/actions/directives/edit-tags.html
  ang/civicase/case/actions/services/edit-tags-case-action.service.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/contact/directives/contact-card.directive.js
  ang/test/civicase/case/actions/services/edit-tags-case-action.service.spec.js
Labels: bug, improvements, regression

#550 CATL-1598: Fix height calculation for crm-editable
  ang/civicase/shared/directives/crm-editable.directive.js
Labels: bug

#547 CATL-1573: Move client to next line in Small Screens
  css/civicase.min.css
  scss/base/_variables.scss
  scss/components/_contact-cases-tab.scss
Labels: enhancement

#551 CATL-1606: Application Performance Optimisation
  ang/civicase/activity/calendar/directives/activities-calendar.directive.js
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/activity/filters/directives/activity-filters.directive.html
  ang/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.html
  ang/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.js
  ang/civicase/bulk-action/directives/bulk-actions-message.directive.html
  ang/civicase/bulk-action/directives/bulk-actions-message.directive.js
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html
  ang/civicase/case/list/directives/case-list-table-first-column-header.html
  ang/civicase/case/list/directives/case-list-table.directive.html
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/shared/directives/panel-query.directive.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.spec.js
  ang/test/civicase/bulk-action/directives/bulk-actions-message.directive.spec.js
  ang/test/civicase/shared/directives/panel-query.directive.spec.js
  api/v3/Activity/Getdayswithactivities.php
Labels: bug, enhancement

#546 CATL-1572: Remove Title from Activity Card when showing Contact's Full Name
  ang/civicase/contact/directives/contact-card.directive.html
Labels: bug

#554 CPS-301: Release v1.6.0
  info.xml
Labels: release

#556 CATL-1642: Remove activity creation api calls
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
Labels: enhancement

#552 CATL-1570: Changes when navigating to Manage Case from Contact Case tab
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
  ang/civicase/case/details/directives/case-details-clear-filters.html
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/case/details/directives/case-details.directive.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/list/directives/case-list-table.directive.html
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/case/search/directives/search.directive.html
  ang/civicase/case/search/directives/search.directive.js
  ang/civicase/shared/directives/edit-custom-data.directive.js
  ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
  css/civicase.min.css
  scss/base/_variables.scss
  scss/components/_case-list-panel.scss
  scss/components/_case-list-table.scss
Labels: enhancement

#558 CATL-1642: Disable UI when case roles exceed limit
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  css/civicase.min.css
  scss/components/_case-peoples.scss
Labels: enhancement

#553 CATL-1505: Increase Tags Visibility
  ang/civicase/case/card/directives/case-card-case-list.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/shared/directives/tags-container.directive.html
  css/civicase.min.css
  scss/components/_case-card.scss
  scss/components/_case-header.scss
  scss/components/_contact-cases-tab.scss
  scss/components/_tags-container.scss
Labels: enhancement

#561 CATL-1587: Single Role per Role type
  CRM/Civicase/Event/Listener/CaseRoleCreation.php
  CRM/Civicase/Service/CaseRoleCreationBase.php
  CRM/Civicase/Service/CaseRoleCreationPostProcess.php
  CRM/Civicase/Service/CaseRoleCreationPreProcess.php
  CRM/Civicase/Test/Fabricator/Relationship.php
  CRM/Civicase/Test/Fabricator/RelationshipType.php
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  civicase.php
  css/civicase.min.css
  phpcs-ruleset.xml
  scss/components/_case-peoples.scss
  settings/CiviCase.setting.php
  tests/phpunit/CRM/Civicase/Helpers/CaseSettingsTrait.php
  tests/phpunit/CRM/Civicase/Helpers/SessionTrait.php
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPostProcessTest.php
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
  tests/phpunit/api/v3/CaseRoleCreationTest.php
  tests/phpunit/bootstrap.php
Labels: enhancement

#562 CPS-305: Release v1.7.0
  info.xml
Labels: release

#564 CATL-1588: Support specifying start date while adding role in people's tab
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
  ang/civicase/case/details/people-tab/services/remove-date-picker-hrefs.service.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  css/civicase.min.css
  package-lock.json
  scss/components/_date-inputs.scss
  scss/components/_form.scss
  scss/overrides/_clear-link.scss
Labels: bug, enhancement, improvements

#565 CATL-1589: Support specifying end date while removing role in people's tab
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  css/civicase.min.css
  scss/components/_contact-prompt-dialog.scss
  scss/components/_form.scss
Labels: new feature

#566 CATL-1590: Specify reassign role date in people's tab
  CRM/Civicase/Service/CaseRoleCreationPostProcess.php
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
Labels: new feature, regression
