Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-06, with the labels that each got.

#473 CATL-1285: Related cases tab
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase-base/decorators/root-scope.decorator.js
  ang/civicase/case/details/configs/add-case-details-tabs.config.js
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/directives/tab-content/linked-cases.html
  ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab--placeholder.directive.html
  ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.html
  ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.js
  ang/civicase/case/details/service/case-details-linked-cases-tab.service.js
  ang/civicase/case/details/summary-tab/case-details-summary-tab.html
  ang/test/civicase-base/decorators/root-scope.decorator.spec.js
  ang/test/civicase/case/details/configs/add-case-details-tabs.config.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.spec.js
  ang/test/civicase/case/details/service/case-details-linked-cases-tab.service.spec.js
  css/civicase.min.css
  scss/components/_case-linked-cases.scss
  settings/CiviCase.setting.php
  tests/backstop_data/engine_scripts/puppet/on-before.js
  tests/backstop_data/gulp-tasks/backstopjs.js
  tests/backstop_data/scenarios/manage-cases.json
Labels: enhancement

#479 RSE-1121: Release v1.1.1
  info.xml
Labels: release

#483 CPS-239: Fix PHP lint error
  phpcs-ruleset.xml
Labels: bug

#476 CATL-1396: Add tags while uploading files from Files tab
  ang/civicase/shared/directives/file-uploader.directive.html
  ang/civicase/shared/directives/file-uploader.directive.js
  ang/test/civicase/shared/directives/file-uploader.directive.spec.js
  ang/test/mocks/services/crm-blocker.factory.mock.js
  css/civicase.min.css
  scss/components/_file-uploader.scss
Labels: new feature

#427 CPS-107: Only display case statuses belonging to loaded case types
  ang/civicase-base/providers/case-type-category.provider.js
  ang/civicase-base/services/case-type-filterer/case-type-filterer.service.js
  ang/civicase-base/services/case-type-filterer/filters/belongs-to-category.service.js
  ang/civicase-base/services/case-type-filterer/filters/has-id.service.js
  ang/civicase-base/services/case-type-filterer/filters/is-included-in-list-of-ids.service.js
  ang/civicase/case/directives/case-overview.directive.html
  ang/civicase/case/directives/case-overview.directive.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/civicase-base/services/case-type-filterer/case-type-filterer.service.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/mocks/data/cases-types.data.js
Labels: enhancement

#495 CATL-1421: Fix Custom Value endpoint
  api/v3/CustomValue/Getalltreevalues.php
Labels: bug

#497 CATL-1437: Fix 'Cases I am involved in' filter text
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: improvements

#477 CATL-1398: Search by tags in Files Tab
  ang/civicase-base/directives/tags-selector.directive.js
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/civicase/case/details/file-tab/directives/file-filter.directive.html
  ang/civicase/case/details/file-tab/directives/file-filter.directive.js
  ang/test/civicase-base/directives/tags-selector.directive.spec.js
  ang/test/civicase/case/details/file-tab/directives/file-filter.directive.spec.js
  api/v3/Case/Getfiles.php
  css/civicase.min.css
  package-lock.json
  scss/components/_case-files.scss
  scss/components/_tags-selector.scss
  tests/backstop_data/package.json
Labels: new feature

#486 CATL-1299: Add 'Last activity' to the Case Panel
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  api/v3/Case/Getdetails.php
Labels: improvements, new feature

#484 CATL-1409: Modify Case Details section in Contact's Case tab
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
Labels: improvements

#489 CATL-1394: Contact Card Email Links
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/activity/panel/directives/activity-panel.directive.html
  ang/civicase/case/card/directives/case-card-case-list.directive.html
  ang/civicase/case/card/directives/case-card-dashboard.directive.html
  ang/civicase/case/card/directives/case-card-other-cases.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/civicase/contact/directives/contact-icon.directive.html
  ang/civicase/contact/directives/contact-icon.directive.js
  ang/civicase/contact/directives/contact-popover-content.directive.html
  ang/civicase/contact/directives/contact-popover-content.directive.js
  ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js
Labels: enhancement

#500 CPS-248: Release v1.2.0
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/activity/panel/directives/activity-panel.directive.html
  ang/civicase/case/card/directives/case-card-case-list.directive.html
  ang/civicase/case/card/directives/case-card-dashboard.directive.html
  ang/civicase/case/card/directives/case-card-other-cases.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/civicase/contact/directives/contact-icon.directive.html
  ang/civicase/contact/directives/contact-icon.directive.js
  ang/civicase/contact/directives/contact-popover-content.directive.html
  ang/civicase/contact/directives/contact-popover-content.directive.js
  ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js
  info.xml
Labels: release

#498 CATL-1179: Remove multi select from Activity Type filter
  ang/civicase/activity/filters/directives/activity-filters.directive.html
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/civicase/case/card/directives/case-activity-count.directive.html
  ang/civicase/case/card/directives/case-card-other-cases.directive.html
  css/civicase.min.css
  scss/components/_activity-filter.scss
Labels: bug, improvements

#503 CATL-1457: Fix Dashboard Tab affix issue
  css/civicase.min.css
  scss/components/_dashboard.scss
Labels: bug, regression

#504 CPS-251: Fix Manage Case Relationship filter
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: bug, regression

#505 CATL-1460: Fix Case Dashboard console errors
  ang/civicase/case/directives/case-overview.directive.js
Labels: bug

#506 CATL-1462: Release v1.2.1
  info.xml
Labels: release

#501 CPS-194: Remove URL parameters added by individual tabs when changing case
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
Labels: bug

#502 CPS-198: Replace `crmApi` with `civicaseCrmApi`
  ang/civicase/activity/actions/services/delete-activity-action.service.js
  ang/civicase/activity/actions/services/move-copy-activity-action.service.js
  ang/civicase/activity/actions/services/tags-activity-action.service.js
  ang/civicase/activity/calendar/directives/activities-calendar.directive.js
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/activity/feed/directives/activity-month-nav.directive.js
  ang/civicase/activity/panel/directives/activity-panel.directive.js
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-list.directive.js
  ang/civicase/case/details/file-tab/directives/file-list.directive.js
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/service/case-details-activity-tab.service.js
  ang/civicase/case/details/service/case-details-files-tab.service.js
  ang/civicase/case/details/service/case-details-people-tab.service.js
  ang/civicase/case/details/service/case-details-summary-tab.service.js
  ang/civicase/case/directives/case-overview.directive.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/case/search/directives/search.directive.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
  ang/civicase/contact/services/contacts-cache.service.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/civicase/shared/directives/api3-ctrl.directive.js
  ang/civicase/shared/directives/file-uploader.directive.js
  ang/civicase/shared/directives/panel-query.directive.js
  ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
  ang/test/civicase/activity/actions/services/tags-activity-action.service.spec.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-month-nav.directive.spec.js
  ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
  ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-list.directive.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
  ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  ang/test/civicase/contact/services/contacts-cache.service.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/civicase/shared/directives/file-uploader.directive.spec.js
  ang/test/civicase/shared/directives/panel-query.directive.spec.js
  ang/test/mocks/services/crm-api.factory.mock.js
Labels: improvements
