Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-11, with the labels that each got.

#620 RSE-1455: Refactor Duplicate Workflow functionality
  CRM/Workflow/Hook/addDependentAngularModules.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
  ang/test/workflow/services/ang/workflow/services/duplicate-workflow-case-management.service.spec.js
  ang/workflow.ang.php
  ang/workflow/action-links/controllers/workflow-duplicate.controller.js
  ang/workflow/services/duplicate-workflow-case-management.service.js
Labels: bug, improvements

#628 CATL-1900: Redirect After Pdf Download
  CRM/Civicase/Hook/BuildForm/AddScriptToCreatePdfForm.php
  CRM/Civicase/Hook/BuildForm/MakePdfFormSubjectRequired.php
  civicase.php
  js/create-pdf-form.js
Labels: new feature

#627 CATL-1799: Restrict Case Email Contacts
  CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
  civicase.php
  js/civicase-settings-form.js
  js/restrict-case-email-contacts.js
  settings/CiviCase.setting.php
Labels: enhancement

#629 CPS-384: Fix PDF Download activity deletion
  civicase.php
Labels: bug

#632 CATL-1938: PDF Download Filename popup
  CRM/Civicase/Hook/BuildForm/PdfFormButtonsLabelChange.php
  js/create-pdf-form.js
Labels: new feature

#633 CPS-386: Release v1.9.5
  info.xml
Labels: release

#637 RSE-1516: Add Client Role To Roles List While Sending Bulk Email
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
Labels: new feature, run backstop

#639 RSE-1528: Create Email did not work for Application Management instance
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/services/cases-utils.service.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/services/cases-utils.service.spec.js
Labels: bug

#648 CPS-397: Fix failing Drupal Build For Unit Test Workflow
  .github/workflows/backstop.yml
  .github/workflows/unit-test.yml
Labels: bug, run backstop
