Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-12, with the labels that each got.

#649 CATL-1981: Fix case linking
  ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.js
  ang/test/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.spec.js
Labels: bug, regression

#653 RSE-1442: Add Bulk Email Activity To All The Selected Cases
  CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCases.php
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
  civicase.php
  tests/phpunit/CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCasesTest.php
Labels: enhancement

#644 RSE-1550: Workflow List new Columns and Filters
  ang/civicase-base/directives/tags-selector.directive.js
  ang/civicase-base/factories/get-select2-value.factory.js
  ang/civicase-base/providers/workflow-list-action-items.provider.js
  ang/civicase-base/providers/workflow-list-columns.provider.js
  ang/civicase-base/providers/workflow-list-filters.provider.js
  ang/civicase-base/services/contacts-cache.service.js
  ang/civicase-base/services/pascal-case.service.js
  ang/civicase-base/services/select2-utils.service.js
  ang/civicase/activity/actions/services/tags-activity-action.service.js
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase-base/providers/workflow-list-columns.provider.spec.js
  ang/test/civicase-base/providers/workflow-list-filters.provider.spec.js
  ang/test/civicase-base/services/contacts-cache.service.spec.js
  ang/test/civicase-base/services/select2-utils.service.spec.js
  ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/test/workflow/services/ang/workflow/services/duplicate-workflow-case-management.service.spec.js
  ang/test/workflow/services/case-management-workflow.service.spec.js
  ang/workflow/action-links/controllers/workflow-duplicate.controller.js
  ang/workflow/columns/directives/workflow-list-column-description.html
  ang/workflow/columns/directives/workflow-list-column-is-enabled.html
  ang/workflow/columns/directives/workflow-list-column-title.html
  ang/workflow/configs/workflow-list-columns.config.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
  ang/workflow/services/case-management-workflow.service.js
  ang/workflow/services/duplicate-workflow-case-management.service.js
  css/civicase.min.css
  scss/components/_workflow-list.scss
Labels: improvements, new feature

#660 RSE-1570: Fix case actions
  ang/civicase-base/providers/case-type.provider.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/test/civicase-base/providers/case-type.provider.spec.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  ang/test/mocks/data/cases-types.data.js
Labels: bug

#664 CPS-414: Fix Mysql8 Reserved Word Issue
  api/v3/Case/Getdetails.php
Labels: bug

#651 RSE-1553: Add Create new button
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/test/workflow/services/case-management-workflow.service.spec.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
  ang/workflow/services/case-management-workflow.service.js
  css/civicase.min.css
  scss/components/_workflow-list.scss
Labels: new feature

#661 RSE-1345: Fix Delete Activity Bug
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.js
Labels: bug
