Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-02, with the labels that each got.

#350 RSE-753: Replace Add New [Case category] Menu URL with Webform URL.
  CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
  CRM/Civicase/Service/CaseCategorySetting.php
  civicase.php
Labels: new feature

#355 RSE-828: Manage Case Tab header Always Shows Manage Cases Regardless of Case Type category
  ang/civicase/case/list/directives/case-list.html
Labels: improvements

#356 RSE-858: Fix view award application details
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
  ang/test/global.js
  ang/test/mocks/data/constants.data.js
Labels: bug, regression

#353 RSE-341: Updated Mock files related to Unit Tests
  ang/test/mocks/data/option-value.data.js
  ang/test/mocks/services/crm-status.factory.mock.js
  api/v3/CustomValue/Gettreevalues.php
Labels: improvements

#357 RSE-882: Fix Issue With Other Relationships Tab Not Showing Up For awards
  CRM/Civicase/Hook/alterAPIPermissions/Case.php
Labels: bug

#358 RSE-363: Filter by Award Status
  ang/civicase/case/directives/case-overview.directive.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
Labels: bug

#360 RSE-747: Update and Translate Case Category Form Settings Description For CiviCase Settings
  CRM/Civicase/Service/CaseCategorySetting.php
  templates/CRM/Civicase/Admin/Form/Settings.tpl
Labels: improvements

#361 RSE-830: Fix: Activity Report Should Reflect Correct Case Type Category
  CRM/Civicase/XMLProcessor/Report.php
Labels: improvements
