Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-03, with the labels that each got.

#364 Fix reference to undefined variable $caseTypes
  ang/civicase-base.ang.php
Labels: improvements

#366 RSE-953: Recalculate scrollbar when case types are fetched
  ang/civicase/case/directives/case-overview.directive.js
Labels: bug

#368 RSE-939: Fix Case Category Permission Issues With Print Report and Activity Page.
  CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
Labels: bug

#367 CATL-1221: Accept URL values for the case relationship type filter
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: improvements

#370 CPS-53: Fix case tabs padding
  ang/civicase/case/details/directives/placeholder/files.html
  ang/civicase/case/details/directives/placeholder/people.html
  ang/civicase/case/details/directives/tab-content/files.html
  ang/civicase/case/details/directives/tab-content/people.html
  css/civicase.min.css
  scss/components/_case-files.scss
  scss/components/_case-peoples.scss
  scss/components/_case-tab.scss
Labels: regression

#373 RSE-745: Fix Case Category Menu/Tabs Issues
  CRM/Civicase/Hook/PostProcess/CaseCategoryMenuLinksProcessor.php
  CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
  CRM/Civicase/Hook/alterAPIPermissions/Case.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
  ang/civicase/case/details/summary-tab/case-summary-tasks.html
  ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
  api/v3/Case/Getfiles.php
Labels: bug

#378 CPS-102: Filter other cases by category
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
Labels: bug

#384 BASWSPRT-98: Apply Relationship Filter to Manage Cases link from Dashboard
  ang/civicase/case/directives/case-overview.directive.html
  ang/civicase/case/directives/case-overview.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.html
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
Labels: bug, improvements

#308 CATL-1132: Block clients from having other roles
  ang/civicase/case/details/people-tab/directives/case-details-people-tab-placeholder.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
Labels: enhancement

#387 CPS-117: Fix Activty Types not shown on Contact Case tab
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
Labels: bug, regression

#386 CPS-122: Fix my role not showing
  ang/civicase/case/factories/format-case.factory.js
Labels: bug

#385 CPS-105: Fix dashboard activity feed
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
Labels: bug

#389 CPS-114: Fix case details link
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: bug, regression

#383 CPS-78: Fix dropdown menu on Firefox
  ang/civicase/shared/directives/dropdown.directive.js
  ang/test/civicase/shared/directives/dropdown.directive.spec.js
Labels: bug

#394 RSE-1000: Fix actions word replacement
  ang/civicase-base/providers/activity-actions.provider.js
Labels: bug

#395 RSE-1028: Fix Add Case link
  CRM/Civicase/Helper/NewCaseWebform.php
  ang/civicase-base.ang.php
  ang/civicase-base/constants.js
  ang/civicase-base/services/case-category-webform-settings.service.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
  ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
  ang/test/mocks/data/constants.data.js
Labels: bug

#397 RSE-1031: Fix translation in Move/Copy Activity Popup
  ang/civicase/activity/actions/services/move-copy-activity-action.service.js
Labels: bug

#372 RSE-678: Relationship Type mock data
  ang/test/mocks/data/relationship-type.data.js
Labels: new feature

#392 RSE-672: Contacts mock data
  ang/test/mocks/data/group.data.js
Labels: improvements

#393 CATL-1248: Fix draft PDF activity form
  CRM/Civicase/Hook/PageRun/ViewCasePageRedirect.php
  CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
  ang/civicase/activity/activity-forms/activity-forms.config.js
  ang/civicase/activity/activity-forms/services/activity-popup-form.service.js
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.js
  ang/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.js
  ang/civicase/activity/activity-forms/services/view-activity-form.service.js
  ang/civicase/activity/factories/check-if-draft-activity.factory.js
  ang/civicase/activity/factories/check-if-draft-email-or-pdf.factory.js
  ang/civicase/activity/panel/directives/activity-panel.directive.html
  ang/civicase/activity/panel/directives/activity-panel.directive.js
  ang/test/civicase/activity/activity-forms/activity-forms.config.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-popup-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/view-activity-form.service.spec.js
  ang/test/civicase/activity/factories/check-if-draft-activity.factory.spec.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  ang/test/global.js
  civicase.php
Labels: bug

#399 CPS-136: [Backstop JS]Tweak contacts dashboard js and associated readme content
  tests/backstop_data/Readme.md
  tests/backstop_data/engine_scripts/puppet/contacts/contact-dashboard.js
Labels: Backstop, improvements

#400 CPS-140: [Backstop JS] - Dashboard section - Add logic for opening filter dropdown and add open case modal screen
  tests/backstop_data/Readme.md
  tests/backstop_data/engine_scripts/puppet/mouse-events-helper.js
  tests/backstop_data/engine_scripts/puppet/utility.js
  tests/backstop_data/scenarios/dashboard.json
Labels: Backstop, new feature

#407 CATL-1252: [Backstop JS] - Activity panel feed - Add screens for activity feed panel section
  tests/backstop_data/Readme.md
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-maximize.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-priority-dropdown.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-status-dropdown.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-add-tag.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-copy-to-case.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-delete.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-move-to-case.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-remove-tag.js
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions.js
  tests/backstop_data/scenarios/activity-feed-panel.json
Labels: Backstop, new feature

#406 RSE-957: Fix Clicking on "Case Category Dashboard" Breadcrumb Takes User to Cases Dashboard
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
  ang/civicase.ang.php
Labels: bug

#164 C51-393: [Backstop JS] Manage Cases - Add screens for manage cases list and selected case
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/list/directives/case-list-table.directive.html
  gulp-tasks/backstopjs.js
  gulpfile.js
  package-lock.json
  package.json
  tests/backstop_data/Readme.md
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/load-more-clicked.js
  tests/backstop_data/engine_scripts/puppet/contacts/contact-dashboard.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/files-tab-upload-file.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-other-relationships-loading.js
  tests/backstop_data/engine_scripts/puppet/on-ready.js
  tests/backstop_data/scenarios/activity-feed-panel.json
  tests/backstop_data/scenarios/manage-cases.json
Labels: Backstop, improvements

#405 RSE-675: Refactor Tags Activity Action
  ang/civicase-base.ang.php
  ang/civicase-base/directives/tags-selector.directive.html
  ang/civicase-base/directives/tags-selector.directive.js
  ang/civicase/activity/actions/services/tags-activity-action.html
  ang/civicase/activity/actions/services/tags-activity-action.service.js
  ang/test/civicase-base/directives/tags-selector.directive.spec.js
  ang/test/civicase/activity/actions/services/tags-activity-action.service.spec.js
  ang/test/mocks/data/tags.data.js
  css/civicase.min.css
  scss/components/_tags-modal.scss
Labels: improvements

#409 RSE-659: Fix Bulk Action Error with Tags
  ang/civicase/activity/actions/services/tags-activity-action.html
Labels: bug, regression

#403 CPS-86: Remove Webforms case action
  ang/civicase.ang.php
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/case/actions/services/webforms-case-action.service.js
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details-header.html
  ang/civicase/case/list/directives/case-list-table-first-column-header.html
  ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js
Labels: enhancement

#401 CPS-81: Fix case subject saving
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
Labels: bug

#412 Merging Awards Sprint 5 to Master
  ang/civicase-base.ang.php
  ang/civicase-base/directives/tags-selector.directive.html
  ang/civicase-base/directives/tags-selector.directive.js
  ang/civicase/activity/actions/services/tags-activity-action.html
  ang/civicase/activity/actions/services/tags-activity-action.service.js
  ang/test/civicase-base/directives/tags-selector.directive.spec.js
  ang/test/civicase/activity/actions/services/tags-activity-action.service.spec.js
  ang/test/mocks/data/group.data.js
  ang/test/mocks/data/relationship-type.data.js
  ang/test/mocks/data/tags.data.js
  css/civicase.min.css
  scss/components/_tags-modal.scss
Labels: new feature

#408 RSE-956: Use form service when adding new activities
  ang/civicase/activity/activity-forms/activity-forms.config.js
  ang/civicase/activity/activity-forms/services/add-activity-form.service.js
  ang/civicase/activity/activity-forms/services/add-custom-path-activity-form.service.js
  ang/civicase/activity/activity-forms/services/update-activity-form.service.js
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/activity/factories/view-in-popup.factory.js
  ang/test/civicase/activity/activity-forms/activity-forms.config.spec.js
  ang/test/civicase/activity/activity-forms/services/add-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/add-custom-path-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/update-activity-form.service.spec.js
Labels: enhancement

#416 RSE-1050: Fix Contact Tab Case Actions
  CRM/Civicase/Page/ContactCaseTab.php
  ang/civicase-base/services/case-actions.service.js
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/test/civicase-base/services/case-actions.service.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
Labels: bug

#168 C51-394: [Backstop JS] - Contact case tab - Add scenarios,
  gulp-tasks/backstopjs.js
  tests/backstop_data/Readme.md
  tests/backstop_data/engine_scripts/puppet/activity-feed-panel/on-contact-page.js
  tests/backstop_data/scenarios/activity-feed-panel.json
  tests/backstop_data/scenarios/contact-case-tab.json
Labels: Backstop, improvements
