Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2020-01, with the labels that each got.

#340 CPS-66: Handle Disabled Activity Types
  CRM/Civicase/Helper/OptionValues.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/civicase-base/services/activity-category.service.js
  ang/civicase-base/services/activity-status.service.js
  ang/civicase-base/services/activity-type.service.js
  ang/civicase-base/services/case-status.service.js
  ang/civicase-base/services/priority.service.js
  ang/civicase/activity/actions/services/edit-activity-action.service.js
  ang/civicase/activity/directives/activity-icon.directive.js
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/activity/factories/format-activity.factory.js
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/civicase/case/actions/services/link-cases-case-action.service.js
  ang/civicase/case/details/directives/case-details.directive.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
  ang/test/civicase/activity/directives/activity-icon.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
  ang/test/civicase/case/details/provider/case-details.provider.spec.js
  ang/test/mocks/data/activity-categories.data.js
  ang/test/mocks/data/activity-statuses.data.js
  ang/test/mocks/data/activity-types.data.js
  ang/test/mocks/data/case-type-category.data.js
  ang/test/mocks/data/cases-statuses.data.js
Labels: bug

#339 CP-67: Fix "Case with Activity Pivot Chart" Report not showing data on civicrm dashboard
  CRM/Civicase/Form/Report/BaseExtendedReport.php
Labels: bug

#343 CPS-68: Activity Calendar Refactor
  ang/civicase/activity/calendar/directives/activities-calendar.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.html
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  api/v3/Activity/Getdayswithactivities.php
Labels: bug, improvements

#345 CPS-69: Show Formatted HTML for Custom fields
  .npmrc 
  .nvmrc
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/summary-tab/case-summary-custom-data.html
  package.json
Labels: bug

#346 CPS-68: change parameter type
  api/v3/Activity/Getdayswithactivities.php
  package-lock.json
Labels: bug, regression

#348 CPS-74: Fix Contact Page Add Case webform link
  ang/civicase/shared/filters/crm-url.filter.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  ang/test/civicase/shared/filters/crm-url.filter.js
  ang/test/civicase/shared/filters/crm-url.filter.spec.js
Labels: bug

#349 CPS-71: Release v1.0.0-beta.3
  ang/civicase/shared/filters/crm-url.filter.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  ang/test/civicase/shared/filters/crm-url.filter.js
  ang/test/civicase/shared/filters/crm-url.filter.spec.js
  info.xml
Labels: release
