Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-05, with the labels that each got.

#766 CPS-545: Remove Pagination from Pivot report
  CRM/Civicase/Form/Report/BaseExtendedReport.php
Labels: bug

#768 CPS-511: Do not allow client to be assigned to existing contacts
  ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.js
  ang/civicase/case/details/people-tab/messages.constants.js
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/directives/case-roles-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
Labels: bug

#782 RSE-1276: Fix for Word Replacements Using Singular and Plural Labels
  CRM/Civicase/Helper/CaseCategory.php
Labels: bug

#760 RSE-1276: Change Case Categories Workflow Labels
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Helper/CaseUrl.php
  CRM/Civicase/Helper/Category.php
  CRM/Civicase/Hook/BuildForm/AddCaseCategoryCustomFields.php
  CRM/Civicase/Hook/BuildForm/AddCaseCategoryInstanceField.php
  CRM/Civicase/Hook/CaseCategoryFormHookBase.php
  CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
  CRM/Civicase/Hook/PostProcess/SaveCaseCategoryCustomFields.php
  CRM/Civicase/Hook/PostProcess/SaveCaseCategoryInstance.php
  CRM/Civicase/Service/CaseCategoryCustomDataType.php
  CRM/Civicase/Service/CaseCategoryCustomFieldsSetting.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
  CRM/Civicase/Service/ManageWorkflowMenu.php
  CRM/Civicase/Setup/ProcessCaseCategoryForCustomGroupSupport.php
  CRM/Civicase/Setup/UpdateCategoryNavigationItems.php
  CRM/Civicase/Upgrader/Steps/Step0016.php
  ang/civicase-base.ang.php
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/mocks/data/case-type-category.data.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
  civicase.php
  templates/CRM/Civicase/Form/CaseCategoryCustomFields.tpl
  tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomFieldsSettingTest.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php
  tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php
Labels: enhancement

#783 CPS-539: Fix Activity Type filter in Activity Feed
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js
  ang/test/civicase/activity/filters/directives/activity-filters.directive.spec.js
  ang/test/mocks/data/activity-types.data.js
  ang/test/mocks/data/cases.data.js
Labels: bug, regression

#786 CPS-595: Add maxLength Attribute to Label Field
  CRM/Civicase/Hook/BuildForm/AddCaseCategoryCustomFields.php
Labels: enhancement

#785 CPS-490: Close PDF popup after Download Document
  ang/civicase/activity/actions/services/resume-draft-activity-action.service.js
  ang/civicase/activity/factories/view-in-popup.factory.js
  ang/civicase/case/details/directives/case-details.directive.js
  ang/test/civicase/activity/factories/view-in-popup.factory.spec.js
  civicase.php
  js/close-pdf-form.js
Labels: improvements

#788 CPS-577: Include Inactive RelationshipTypes on View
  ang/civicase-base.ang.php
  ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
Labels: bug

#793 Remove reference to undefined variable
  ang/workflow.ang.php
Labels: bug
