Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-01, with the labels that each got.

#652 RSE-1554: Support for separate "Edit Workflow" page for individual instance
  ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
  ang/test/workflow/services/case-management-workflow.service.spec.js
  ang/workflow/action-links/controllers/workflow-edit.controller.js
  ang/workflow/action-links/directives/workflow-list-edit-action.html
  ang/workflow/services/case-management-workflow.service.js
Labels: new feature

#668 CATL-2016: Fix Issue while resuming draft
  CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
  ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.js
  ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.spec.js
Labels: bug

#669 CPS-417: Fix Bug With Recent Communication Block
  ang/civicase/activity/factories/view-in-popup.factory.js
  ang/test/civicase/activity/factories/view-in-popup.factory.spec.js
Labels: bug

#672 RSE-1376: Fix Bug Downloading All Files On Awards
  CRM/Civicase/Page/ActivityFiles.php
  CRM/Civicase/Service/CaseCategoryFromUrl.php
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  config/urls/case_category_url.php
Labels: bug

#673 RSE-1600: Support for instance specific Action Items
  ang/civicase-base/providers/workflow-list-action-items.provider.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow/directives/workflow-list.directive.js
Labels: new feature

#674 CPS-438: Release v1.9.9
  info.xml
Labels: release

#676 CPS-403: Fix Deprecated Case Permission
  CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
Labels: bug

#655 CPS-402: Fix Avatar Initials
  ang/civicase-base/services/contacts-cache.service.js
  ang/civicase/contact/directives/contact-card.directive.js
  ang/test/civicase-base/services/contacts-cache.service.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-email-case-manager.js
Labels: bug, run backstop

#678 RSE-1596: Show disabled cases on Contact's case tabs
  ang/civicase-base/directives/checkbox.directive.html
  ang/civicase-base/directives/checkbox.directive.js
  ang/civicase.ang.php
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/activity/factories/format-activity.factory.js
  ang/civicase/activity/factories/view-in-popup.factory.js
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/case/actions/services/change-status-case-action.service.js
  ang/civicase/case/card/directives/case-card-contact-record.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/factories/format-case.factory.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/case/search/directives/search.directive.html
  ang/civicase/case/search/directives/search.directive.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/test/civicase-base/directives/checkbox.directive.spec.js
  ang/test/civicase-base/services/case-actions.service.spec.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
  ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js
  ang/test/civicase/activity/factories/view-in-popup.factory.spec.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/mocks/data/case-actions.data.js
  css/civicase.min.css
  scss/components/_case-search.scss
  scss/components/_checkbox.scss
Labels: improvements

#679 RSE-1597: Block disabled cases details
  ang/civicase-base/providers/activity-actions.provider.js
  ang/civicase/activity/actions/directives/activity-actions.directive.js
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-menu.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/directives/case-details-header.directive.html
  ang/civicase/case/details/directives/case-details-tabs.directive.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html
  ang/civicase/case/details/people-tab/directives/relationships-tab.directive.html
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/summary-tab/case-details-summary-next-milestone.html
  ang/civicase/case/details/summary-tab/case-details-summary-next-non-milestone-activity.html
  ang/civicase/case/details/summary-tab/directives/case-summary-recent-communications.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-tasks.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary.directive.html
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/test/civicase/activity/actions/directives/activity-actions.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
  css/civicase.min.css
  scss/components/_activity-card--big.scss
Labels: Backstop, enhancement

#663 CPS-409: Add tests for CategoryFromUrl class
  CRM/Civicase/Service/CaseCategoryFromUrl.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryFromUrlTest.php
Labels: improvements

#683 CPS-366: Fix Custom Group Ordering
  ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
Labels: bug

#677 CATL-2031: Use date fields stored inside of relationship object
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
Labels: bug

#685 CATL-2030: Add date range limits to role inline date pickers
  ang/civicase-base/directives/inline-datepicker.directive.js
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/test/civicase-base/directives/inline-datepicker.directive.spec.js
Labels: bug

#650 CATL-1990: Limit Recipient And Cc/Bcc Fields To Only The Selected Contacts
  CRM/Civicase/Hook/BuildForm/LimitRecipientFieldsToOnlySelectedContacts.php
  CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
  civicase.php
  js/restrict-email-contacts.js
  settings/CiviCase.setting.php
Labels: improvements

#687 RSE-1627: Update disabled cases filter label
  ang/civicase/case/search/directives/search.directive.html
Labels: improvements

#686 RSE-1625: Fix disabled cases stats
  api/v3/Case/Getstats.php
Labels: bug

#682 RSE-1565: Fix logic for showing Milestone Activities
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  api/v3/Activity/Getcontactactivitiescount.php
Labels: bug, regression

#665 CATL-1948: Fix missing end dates
  CRM/Civicase/Service/CaseRoleCreationPostProcess.php
  ang/civicase-base/directives/inline-datepicker.directive.js
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase-base/directives/inline-datepicker.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPostProcessTest.php
Labels: bug
