Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-02, with the labels that each got.

#690 CPS-450: Fix Email Draft Forms
  ang/civicase/activity/activity-forms/activity-forms.config.js
  ang/civicase/activity/activity-forms/services/activity-form-services/add-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/add-custom-path-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/draft-email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/draft-pdf-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/update-activity-form.service.js
  ang/civicase/activity/activity-forms/services/get-activity-form-url.service.js
  ang/civicase/activity/factories/view-in-popup.factory.js
  ang/test/civicase/activity/activity-forms/activity-forms.config.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/add-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/add-custom-path-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/draft-email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/draft-pdf-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/update-activity-form.service.spec.js
  ang/test/civicase/activity/factories/view-in-popup.factory.spec.js
Labels: regression

#689 CATL-2046: Token Tree Widget
  CRM/Civicase/Hook/BuildForm/TokenTree.php
  CRM/Civicase/Hook/Tokens/AddContactTokens.php
  CRM/Civicase/Hook/Tokens/AddContactTokensValues.php
  CRM/Civicase/Service/ContactCustomFieldsProvider.php
  civicase.php
  js/token-tree.js
  tests/phpunit/CRM/Civicase/Hook/Tokens/AddContactTokenValuesTest.php
Labels: enhancement, improvements

#691 CPS-449: Release v1.10.0-rc
  info.xml
Labels: release

#680 RSE-1295: Override Case Type core screen functionality
  ang/test/workflow/crm/case-type.controller.spec.js
  ang/workflow.ang.php
  ang/workflow/crm/case-type.controller.js
  ang/workflow/crm/override-case-type.config.js
  templates/CRM/Civicase/ChangeSet/CaseTypeCategory.html
Labels: improvements

#695 ACU-493: Add CRM Date Filter and Empty Case Tabs styles
  ang/civicase-base/filters/crm-date.filter.js
  ang/test/civicase-base/filters/crm-date.filter.spec.js
  css/civicase.min.css
  gulp-tasks/karma-unit-test.js
  gulpfile.js
  scss/civicase.scss
  scss/components/_case-tab.scss
Labels: enhancement

#699 ACU-494: Update date range directive
  ang/civicase/shared/directives/ui-date-range.directive.html
  ang/civicase/shared/directives/ui-date-range.directive.js
Labels: bug, improvements, run backstop

#697 ACU-500: Payment Actions
  ang/civicase-base/services/activity-status.service.js
  ang/civicase/activity/actions/services/delete-activity-action.service.js
  ang/civicase/activity/panel/directives/activity-panel.directive.js
  ang/test/civicase-base/services/activity-status.service.spec.js
  ang/test/civicase/activity/actions/services/delete-activity-action.service.spec.js
  ang/test/mocks/data/activity-statuses.data.js
  css/civicase.min.css
  scss/components/_button.scss
Labels: bug, new feature

#701 ACU-495: Add civicase paging component
  ang/civicase-base.ang.php
  ang/civicase-base/directives/paging.html
  ang/civicase-base/directives/paging.js
Labels: enhancement

#702 CATL-2083: Tree Token Selector Bug fixes
  css/civicase.min.css
  js/token-tree.js
  scss/overrides/_crm-token-selector.scss
Labels: bug

#705 CATL-2096: Add Default Value To Relationship Id
  CRM/Civicase/Service/CaseRoleCreationPreProcess.php
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
Labels: bug

#712 CPS-467: Fix Checkbox Styles
  css/civicase.min.css
  scss/components/_checkbox.scss
Labels: bug, regression, run backstop

#713 CATL-2113: Fix treeselect styles
  css/civicase.min.css
  scss/base/_variables.scss
  scss/pages/_case-angular.scss
Labels: bug

#711 CPS-466: Release v1.11.0
  css/civicase.min.css
  info.xml
  scss/base/_variables.scss
  scss/components/_checkbox.scss
  scss/pages/_case-angular.scss
Labels: release, run backstop

#692 RSE-1588: Add Pagination to Manage Workflow and Dashboard Page
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type.provider.js
  ang/civicase-base/services/case-management-workflow.service.js
  ang/civicase-base/services/case-type-filterer/case-type-filterer.service.js
  ang/civicase-base/services/case-type-filterer/filters/belongs-to-category.service.js
  ang/civicase-base/services/case-type-filterer/filters/has-id.service.js
  ang/civicase-base/services/case-type-filterer/filters/is-active.service.js
  ang/civicase-base/services/case-type-filterer/filters/is-included-in-list-of-ids.service.js
  ang/civicase-base/services/get-service-for-instance.js
  ang/civicase.ang.php
  ang/civicase/case/directives/case-overview.directive.html
  ang/civicase/case/directives/case-overview.directive.js
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.html
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/civicase/dashboard/directives/dashboard.directive.html
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase-base/services/case-management-workflow.service.spec.js
  ang/test/civicase-base/services/case-type-filterer/case-type-filterer.service.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/test/workflow/services/case-management-workflow.service.spec.js
  ang/workflow/directives/workflow-list.directive.html
  ang/workflow/directives/workflow-list.directive.js
  css/civicase.min.css
  scss/components/_case-overview.scss
Labels: enhancement, improvements, new feature

#704 ACU-417: Awards Payments Management
  CRM/Civicase/Hook/BuildForm/CaseCategoryCustomGroupDisplay.php
  ang/civicase-base/directives/paging.html
  ang/civicase-base/directives/paging.js
  ang/civicase-base/filters/crm-date.filter.js
  ang/civicase-base/services/activity-status.service.js
  ang/civicase/activity/actions/services/delete-activity-action.service.js
  ang/civicase/activity/panel/directives/activity-panel.directive.js
  ang/civicase/shared/directives/ui-date-range.directive.html
  ang/civicase/shared/directives/ui-date-range.directive.js
  ang/test/civicase-base/filters/crm-date.filter.spec.js
  ang/test/civicase-base/services/activity-status.service.spec.js
  ang/test/civicase/activity/actions/services/delete-activity-action.service.spec.js
  ang/test/mocks/data/activity-statuses.data.js
  css/civicase.min.css
  gulp-tasks/karma-unit-test.js
  gulpfile.js
  scss/civicase.scss
  scss/components/_button.scss
  scss/components/_case-tab.scss
Labels: enhancement, run backstop

#716 RSE-1551: Hide New Case Type button on Case Type list
  CRM/Civicase/Hook/alterAngular/AngularChangeSet.php
  civicase.php
Labels: improvements
