Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-06, with the labels that each got.

#801 CPS-630: Fix syntax error on upgrader
  CRM/Civicase/Setup/UpdateCategoryNavigationItems.php
Labels: bug

#784 CPS-575: Fix page level Permissions
  ang/civicase-base/directives/access-denied.directive.html
  ang/civicase-base/directives/acess-denied.directive.js
  ang/civicase.ang.php
  ang/civicase/app.routes.js
Labels: bug

#797 CPS-501: Fix files tab Activity Category filters
  ang/civicase/case/details/file-tab/directives/file-filter.directive.js
  ang/test/civicase/case/details/file-tab/directives/file-filter.directive.spec.js
Labels: bug

#799 CPS-537: Capitalise first letter of Contact Details Menu
  CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
Labels: improvements

#791 RSESPRT-45: Fix Limitation Between Custom Groups and Custom Types
  CRM/Civicase/Helper/InstanceCustomGroupPostProcess.php
Labels: bug

#800 ACU-594: Add Map and Select classes for exporting cases
  CRM/Case/Export/Form/Map.php
  CRM/Case/Export/Form/Select.php
  CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
Labels: bug

#803 BASWSPRT-275: Fix Missing Pivot Date Data
  CRM/Civicase/Form/Report/BaseExtendedReport.php
Labels: regression

#807 CPS-655: Fix new site deployments
  CRM/Civicase/Setup/AddSingularLabels.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0016.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomFieldsSettingTest.php
Labels: bug, regression

#804 ACU-596: Allow Multiple Cases In Bulk Emails
  CRM/Civicase/Hook/ValidateForm/SendBulkEmail.php
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
  civicase.php
  tests/phpunit/CRM/Civicase/Hook/ValidateForm/SendBulkEmailTest.php
  tests/phpunit/Helpers/MailHelpersTrait.php
  tests/phpunit/bootstrap.php
Labels: enhancement

#805 RSESPRT-55: Edit instance instead of creating if it already exists
  CRM/Civicase/Service/CaseCategoryInstance.php
Labels: bug
