Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-03, with the labels that each got.

#715 CATL-2119: Fix Client Role Display On Peoples Tab
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
Labels: bug

#719 CPS-471: Release v1.12.0
  info.xml
Labels: release

#684 BASWSPRT-166: Fix for Frozen Screen in Activity Feed
  CRM/Civicase/Hook/Tabset/ActivityTabModifier.php
  ang/civicase/activity/calendar/directives/activities-calendar.directive.js
  ang/civicase/activity/card/directives/activity-card-big.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/card/directives/activity-card-short.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.js
  ang/civicase/activity/filters/directives/activity-filters.directive.js
  ang/civicase/activity/panel/directives/activity-panel.directive.html
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/factories/get-case-query-params.factory.js
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/contact/directives/contact-card.directive.js
  ang/civicase/dashboard/directives/dashboard-tab.directive.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
  ang/test/civicase/contact/directives/contact-card.directive.spec.js
  ang/test/mocks/data/cases.data.js
  api/v3/Activity/Getall.php
  api/v3/Case/Getdetails.php
  css/civicase.min.css
  scss/components/_contact-card.scss
Labels: bug, improvements

#723 CPS-464: Use Correct Release PR Github Action version
  .github/workflows/release-pr.yml
Labels: bug

#729 CATL-2136: Delete Draft Email when sending email
  CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php
  CRM/Civicase/Hook/PostProcess/HandleDraftActivity.php
  civicase.php
Labels: bug, regression

#730 CATL-2137: Show "Email-Send Now" case action only in bulk action
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/test/civicase/case/actions/services/email-case-action.service.spec.js
Labels: improvements

#731 CATL-2138: Fix Email activity UI inside Activity Panel
  ang/civicase/activity/actions/services/download-all-action.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/add-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/add-custom-path-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/draft-email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/draft-pdf-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/email-activity-form.service.js
  ang/civicase/activity/activity-forms/services/activity-form-services/update-activity-form.service.js
  ang/civicase/activity/activity-forms/services/get-activity-form-url.service.js
  ang/civicase/activity/activity-forms/services/view-activity-form.service.js
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/civicase/case/actions/services/go-to-webform-case-action.service.js
  ang/civicase/case/actions/services/print-case-action.service.js
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.js
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/services/add-case.service.js
  ang/civicase/contact/directives/contact-card.directive.js
  ang/civicase/contact/directives/contact-popover-content.directive.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/civicase/shared/directives/edit-custom-data.directive.js
  ang/civicase/shared/directives/file-uploader.directive.js
  ang/civicase/shared/filters/crm-url.filter.js
  ang/test/civicase/activity/actions/services/download-all-action.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/add-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/add-custom-path-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/draft-email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/draft-pdf-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/email-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/activity-forms-services/update-activity-form.service.spec.js
  ang/test/civicase/activity/activity-forms/services/view-activity-form.service.spec.js
  ang/test/civicase/activity/panel/directives/activity-panel.directive.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.spec.js
  ang/test/civicase/case/services/add-case.service.spec.js
  ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js
  ang/test/civicase/shared/filters/crm-url.filter.spec.js
  ang/test/mocks/services/crm-url.service.mock.js
  ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
  ang/workflow/action-links/controllers/workflow-duplicate.controller.js
  ang/workflow/action-links/controllers/workflow-edit.controller.js
Labels: bug, regression

#722 CATL-1442: Fix Case Filter order
  ang/civicase/case/list/directives/case-list-table.directive.js
  ang/civicase/case/search/directives/search.directive.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
Labels: improvements

#732 CATL-2139: Show All Relationships in People's tab
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
Labels: bug

#733 CATL-2143: Show print merge case action only in bulk action
  ang/civicase/case/actions/services/print-merge-case-action.service.js
  ang/test/civicase/case/actions/services/print-merge-case-action.service.spec.js
Labels: enhancement

#734 CATL-2140: Fix CC BCC field
  CRM/Civicase/Hook/BuildForm/LimitRecipientFieldsToOnlySelectedContacts.php
  CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
  js/restrict-email-contacts.js
Labels: bug

#735 CATL-2142: Do Not Recreate Existent Relationships
  CRM/Civicase/Event/Listener/CaseRoleCreation.php
  tests/phpunit/api/v3/CaseRoleCreationTest.php
Labels: bug

#726 CPS-478: Add tests for CaseCategoryCustomDataType class
  tests/phpunit/CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCasesTest.php
  tests/phpunit/CRM/Civicase/Hook/SelectWhereClause/LimitCaseQueryToAccessibleCaseCategoriesTest.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomDataTypeTest.php
Labels: improvements

#742 CPS-393: Generate CSS files
  .github/workflows/backstop.yml
Labels: bug

#740 CPS-445: Fix Custom Field UI
  css/civicase.min.css
  scss/components/_case-summary-fields.scss
Labels: bug

#741 CPS-477: Add Tests for CaseCategoryMenu class
  CRM/Civicase/Service/CaseCategoryInstance.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Test/Fabricator/CaseCategory.php
  CRM/Civicase/Test/Fabricator/CaseCategoryInstanceType.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryInstanceTest.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php
  tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php
Labels: improvements

#744 CPS-480: Change button markup
  CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php
Labels: bug

#746 CPS-495: Fix People Tab pagination
  ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
Labels: bug, regression

#745 CATL-2154: Fix custom data blocks sort order
  ang/civicase/case/details/directives/case-details.directive.js
  ang/civicase/case/factories/format-case.factory.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/case/factories/format-case.factory.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/mocks/services/format-case.factory.mock.js
Labels: regression

#717 CPS-427: Civicase alignment with CiviCRM 5.35
  .github/workflows/unit-test.yml
  CRM/Civicase/APIHelpers/CaseDetails.php
  CRM/Civicase/Helper/GlobRecursive.php
  CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php
  CRM/Civicase/Page/DashboardTabs.php
  CRM/Civicase/Upgrader/Base.php
  ang/civicase-base.ang.php
  ang/civicase.ang.php
  ang/civicase/activity/directives/add-activity-menu.directive.js
  ang/civicase/activity/factories/get-activity-feed-url.factory.js
  ang/civicase/crm-dashboard/directives/crm-dashboard-tabset-affix.directive.js
  ang/civicase/crm-dashboard/directives/my-activities-tab.directive.html
  ang/civicase/crm-dashboard/directives/my-activities-tab.directive.js
  ang/test/civicase-base/services/case-management-workflow.service.spec.js
  ang/test/civicase-base/services/contacts-cache.service.spec.js
  ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
  ang/test/civicase/activity/actions/services/tags-activity-action.service.spec.js
  ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
  ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js
  ang/test/civicase/activity/filters/directives/activity-filters.directive.spec.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/civicase/case/details/directives/case-details.directive.spec.js
  ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
  ang/test/civicase/shared/directives/popover.directive.spec.js
  ang/test/karma.conf.js
  ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
  ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
  ang/test/workflow/crm/case-type.controller.spec.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/test/workflow/mocks/routes.mock.js
  ang/test/workflow/mocks/workflow.module.mock.js
  ang/workflow.ang.php
  api/v3/Activity/Getmonthswithactivities.php
  civicase.civix.php
  civicase.php
  phpcs-ruleset.xml
  templates/CRM/Civicase/Page/DashboardTabs.tpl
  xml/Menu/civicase.xml
Labels: bug, enhancement
