Repository compucorp/uk.co.compucorp.civicase, pull requests merged in 2021-04, with the labels that each got.

#743 CPS-487: Capitalize Category Name on Label Menus
  CRM/Civicase/Service/CaseCategoryMenu.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php
Labels: improvements

#739 CPS-494: Fix View All links
  ang/civicase/case/details/summary-tab/directives/case-summary-recent-communications.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary-tasks.directive.html
Labels: bug

#748 CPS-519: Added pagination to the "Other Relationship" sub tab of People Tab
  .github/workflows/linters.yml
  .htmlhintrc
  .lintstagedrc
  ang/civicase/activity/actions/directives/activity-actions.directive.html
  ang/civicase/activity/card/directives/activity-card-long.directive.html
  ang/civicase/activity/feed/directives/activity-feed.directive.html
  ang/civicase/case/card/directives/case-activity-count.directive.html
  ang/civicase/case/details/directives/tab-content/people.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab-placeholder.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
  ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
  ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.js
  ang/civicase/case/details/people-tab/directives/other-relationships-tab.directive.html
  ang/civicase/case/details/people-tab/directives/other-relationships-tab.directive.js
  ang/civicase/case/details/people-tab/directives/relationship-letter-filter.directive.html
  ang/civicase/case/details/people-tab/directives/relationship-letter-filter.directive.js
  ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
  ang/civicase/case/search/directives/search.directive.html
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
  ang/civicase/contact/directives/contact-card.directive.html
  ang/civicase/shared/directives/file-uploader.directive.html
  ang/test/civicase-base/services/relationship-type.service.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/case-roles-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/other-relationships-tab.directive.spec.js
  ang/test/civicase/case/details/people-tab/directives/relationship-letter-filter.directive.spec.js
  ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
  ang/test/mocks/data/other-relationships.data.js
  ang/test/mocks/data/relationship-type.data.js
  api/v3/Case/Getrelations.php
  api/v3/Case/Getrelationscount.php
  css/civicase.min.css
  package-lock.json
  package.json
  scss/components/_case-peoples.scss
Labels: enhancement

#759 RSESPRT-36: Fix Case Tokens icons
  CRM/Civicase/Hook/BuildForm/TokenTree.php
  js/token-tree.js
  tests/phpunit/CRM/Civicase/Hook/BuildForm/TokenTreeTest.php
Labels: improvements

#755 CATL-1660: Fix Select 2 styles
  .github/workflows/backstop.yml
  .github/workflows/linters.yml
  .github/workflows/unit-test.yml
  .nvmrc
  css/civicase.min.css
  package-lock.json
  package.json
  scss/overrides/_forms.scss
  tests/backstop_data/package.json
Labels: bug, enhancement

#747 CPS-39: Fix special characters in case subjects
  ang/civicase-base/filters/escape-string.filter.js
  ang/civicase/case/card/directives/case-card-contact-record.directive.html
  ang/civicase/case/card/directives/case-card-dashboard.directive.html
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
  ang/civicase/case/details/summary-tab/directives/case-summary.directive.html
  ang/civicase/case/factories/format-case.factory.js
  ang/civicase/shared/directives/crm-editable.directive.js
  ang/test/civicase-base/filters/escape-string.spec.js
  ang/test/civicase/case/factories/format-case.factory.spec.js
Labels: bug

#762 ACUSPRT-81: Revert icons
  js/token-tree.js
Labels: regression

#770 CPS-573: Fix Add case
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
Labels: bug

#771 CPS-572: Fix Case link in Activity card
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
Labels: bug, regression

#763 CPS-430: Fix Case Statuses sort order
  ang/civicase/case/directives/case-overview.directive.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
Labels: bug

#764 CPS-261: Fix Error on Case Reports with Hyphen Characters
  CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
  phpcs-ruleset.xml
Labels: bug

#769 CPS-512: Fix Add Activity button in Contact Case Tab
  ang/civicase/activity/card/directives/activity-card-short.directive.html
Labels: bug, regression

#756 CPS-201: Allow Long Case Category Names For Menus
  CRM/Civicase/Helper/CaseCategory.php
  CRM/Civicase/Helper/CaseUrl.php
  CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForNewCase.php
  CRM/Civicase/Hook/BuildForm/FilterCaseTypesByCategoryForNewCase.php
  CRM/Civicase/Hook/Helper/CaseTypeCategory.php
  CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
  CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
  CRM/Civicase/Hook/PreProcess/CaseTypeCategoryWebFormRedirect.php
  CRM/Civicase/Service/CaseCategoryFromUrl.php
  CRM/Civicase/Service/CaseCategoryMenu.php
  CRM/Civicase/Service/ManageWorkflowMenu.php
  CRM/Civicase/Setup/AddManageWorkflowMenu.php
  CRM/Civicase/Setup/MoveCaseTypesToCasesCategory.php
  CRM/Civicase/Setup/UpdateCasesNavigationItems.php
  CRM/Civicase/Setup/UpdateCategoryNavigationItems.php
  CRM/Civicase/Upgrader.php
  CRM/Civicase/Upgrader/Steps/Step0015.php
  ang/civicase-base.ang.php
  ang/civicase-base/providers/case-type-category.provider.js
  ang/civicase.ang.php
  ang/civicase/activity/card/directives/activity-card.directive.js
  ang/civicase/case/actions/services/email-case-action.service.js
  ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
  ang/civicase/case/directives/case-overview.directive.js
  ang/civicase/case/search/directives/search.directive.js
  ang/civicase/case/services/add-case.service.js
  ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
  ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
  ang/civicase/dashboard/directives/dashboard.directive.js
  ang/test/civicase-base/providers/case-type-category.provider.spec.js
  ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
  ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
  ang/test/civicase/case/directives/case-overview.directive.spec.js
  ang/test/civicase/case/search/directives/search.directive.spec.js
  ang/test/civicase/case/services/add-case.service.spec.js
  ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
  ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
  ang/test/global.js
  ang/test/mocks/data/constants.data.js
  ang/test/workflow/crm/case-type.controller.spec.js
  ang/test/workflow/directives/workflow-list.directive.spec.js
  ang/workflow/crm/case-type.controller.js
  ang/workflow/directives/workflow-list.directive.js
  civicase.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryFromUrlTest.php
  tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php
  tests/phpunit/CRM/Civicase/Service/ManageWorkflowMenuTest.php
Labels: improvements

#767 CPS-554: Changes to support CiviProspect
  CRM/Civicase/Service/ManageWorkflowMenu.php
  ang/civicase/case/actions/directives/case-actions.directive.js
  ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
  ang/test/mocks/data/case-category-instance-mapping.data.js
  ang/test/mocks/data/case-category-instance-type.data.js
Labels: enhancement
